[tls.stores]
    [tls.stores.default]
        [tls.stores.default.defaultCertificate]
            certFile = "/certs/live/stage.example.com/fullchain.pem"
            keyFile = "/certs/live/stage.example.com/privkey.pem"
